### PR TITLE
Add automatic electron builds

### PR DESCRIPTION
**Pull request by juliangruber**
Whenever this builds on linux for a node version that has a matching electron version, also builds for electron. This should take care of all electron needs!

### CODE REVIEW

**Comment by juliangruber** [comment]
cc @ralphtheninja @lgeiger @mafintosh @maxogden

**Comment by juliangruber** [comment]
zero configuration required!

**Comment by ralphtheninja** [comment]
Haha!

**Comment by juliangruber** [comment]
2.0.0

**Pull request merged**
